version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - redis
    environment:
      - "REDIS_HOST:redis"
      - "REDIS_PORT:6379"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes