version: '3'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
    tty: true
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - main
networks:
  main:
    external: true